[client]
# Hide the toolbar completely
toolbarMode = "viewer"
showErrorDetails = false

[ui]
# Hide menu and footer
hideTopBar = true
hideSidebarNav = false

[browser]
# Optional: Set the app to use the full width
gatherUsageStats = false

[server]
# Optional: Disable CORS warnings
enableCORS = false
enableXsrfProtection = true
